dbt_poc:
  target: dev
  outputs:
    dev:
      type: synapse
      driver: 'ODBC Driver 17 for SQL Server'
      server: "{{ env_var('SYNAPSE_SERVER') }}"
      port: 1433
      database: "{{ env_var('DABATASE_SYNAPSE') }}"
      schema: "{{ env_var('SCHEMA_SYNAPSE') }}"
      authentication: "{{ env_var('AUTHENTICATION_SYNAPSE') }}"
      user: "{{ env_var('USER_SYNAPSE') }}"
      password: "{{ env_var('PASSWORD_SYNAPSE') }}"
      threads: 4

    pro:
      type: synapse
      driver: 'ODBC Driver 17 for SQL Server'
      server: "{{ env_var('SYNAPSE_SERVER') }}"
      port: 1433
      database: "{{ env_var('DABATASE_SYNAPSE') }}"
      schema: "{{ env_var('SCHEMA_SYNAPSE') }}"
      authentication: "{{ env_var('AUTHENTICATION_SYNAPSE') }}"
      user: "{{ env_var('USER_SYNAPSE') }}"
      password: "{{ env_var('PASSWORD_SYNAPSE') }}"      
      threads: 4