{{
  config(
    materialized='view'
  )
}}

  WITH snapshot_proyecto AS (
    SELECT
        Id,
        IdEstadoProyecto,
        IdAgrupacionEstados,
        CodTipoProyecto,
        IdUnidadMedidaDefecto,
        Codigo,
        CodPais,
        CodMoneda,
        Descripcion,
        CodTipoEstructuraSocietaria,
        CodModoTrabajoPresupuesto,
        CodTipoDepartamento,
        TransferenciaCoste,
        GestorProyecto,
        DiasPlazoPeriodo,
        LimiteTramo,
        DiaInicio,
        DiaFin,
        Activo,
        SistemaRrhhExterno,
        ImportacionNominaExterna,
        TieneRegistroProduccion,
        DesviacionesHorario,
        CodContabilidad,
        CodLimiteConsumo,
        Tolerancia,
        Tasas,
        ProvisionFinObra,
        FechaBaja,
        NoCertificacionAdicionalPdt,
        EnviarProvision,
        Comprometido,
        EsDepartamento,
        PrecierreCentralizado,
        Ofertas,
        IdGrupoProyecto,
        NoSeleccionablePermisos,
        CodSubtipoObra,
        ResponsablePais,
        Delegado,
        Delegacion,
        JefeAdministracion,
        dbt_scd_id,
        dbt_updated_at,
        dbt_valid_from,
        dbt_valid_to
    FROM {{ ref('snapshot_geos__proyecto') }}
  ),

  rename_stg_proyecto AS (
    SELECT
        dbt_scd_id AS sk_proyecto,
        Id AS nk_proyecto,
        IdEstadoProyecto AS id_estado_proyecto,
        IdAgrupacionEstados AS id_agrupacion_estados,
        CodTipoProyecto AS codigo_tipo_proyecto,
        IdUnidadMedidaDefecto AS id_unidad_medida_defecto,
        Codigo AS codigo,
        CodPais AS codigo_pais,
        CodMoneda AS codigo_moneda,
        Descripcion AS descripcion,
        CodTipoEstructuraSocietaria AS codigo_tipo_estructura_societaria,
        CodModoTrabajoPresupuesto AS codigo_modo_trabajo_presupuesto,
        CodTipoDepartamento AS codigo_tipo_departamento,
        TransferenciaCoste AS transferencia_coste,
        GestorProyecto AS gestor_proyecto,
        DiasPlazoPeriodo AS dias_plazo_periodo,
        LimiteTramo AS limite_tramo,
        DiaInicio AS dia_inicio,
        DiaFin AS dia_fin,
        Activo AS activo,
        SistemaRrhhExterno AS sistema_rrhh_externo,
        ImportacionNominaExterna AS importacion_nomina_externa,
        TieneRegistroProduccion AS tiene_registro_produccion,
        DesviacionesHorario AS desviaciones_horarios,
        CodContabilidad AS codigo_contabilidad,
        CodLimiteConsumo AS codigo_limite_consumo,
        Tolerancia AS tolerancia,
        Tasas AS tasas,
        ProvisionFinObra AS provision_fin_obra,
        FechaBaja AS fecha_baja,
        NoCertificacionAdicionalPdt AS no_certificacion_adicional_pdt,
        EnviarProvision AS enviar_provision,
        Comprometido AS comprometido,
        EsDepartamento AS es_departamento,
        PrecierreCentralizado AS precierre_centralizado,
        Ofertas AS ofertas,
        IdGrupoProyecto AS id_grupo_proyecto,
        NoSeleccionablePermisos AS no_seleccionable_permisos,
        CodSubtipoObra AS codigo_subtipo_obra,
        ResponsablePais AS responsable_pais,
        Delegado AS delegado,
        Delegacion AS delegacion,
        JefeAdministracion AS jefe_administracion,
        dbt_valid_from AS fecha_insercion,
        dbt_updated_at AS fecha_modificacion,
        null AS fecha_eliminacion,
        dbt_valid_from AS fecha_desde,
        dbt_valid_to AS fecha_hasta,
        CASE WHEN dbt_valid_to IS NULL THEN 1 ELSE 0 END AS actual
    FROM snapshot_proyecto
  )

  SELECT * FROM rename_stg_proyecto
